### ISSUE TITLE
Python and C++ speed

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#121]
We need to have a lesson on cmake as we use the same in SDC 
(Moving in C++) Good, but students may be confused here. Hitting submit answer re-runs the code, and it gives a different answer than the previous run with the test code. In my case, it looks like part of the code may have been cached, because my first test run ran in about ~27 seconds, but all future runs ran in ~16

**Comment by andrewpaster** [comment]
I'm guessing this comment was from somebody in SDC and was beta testing Intro. We ended up using the embedded C++ workspaces and gave instructions for installing an IDE instead of using something like cmake. Not sure about the code caching or how it would make a difference. The code isn't measure compile time.
