### ISSUE TITLE
Route Planner Project

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#129]
A student expressed graph could be mistaken for an abstract representation of a map. However, it is quite literal in its expression of distance and connectivity.  For Instance, instructions like "on the graph below, the edge between 2 nodes represents a literal straight road not just a connection of 2 cities. etc."

**Comment by davinderc** [comment]
It may be appropriate to scale up all of the distances by 100 to make them more life-like, so that students see these values as miles or kilometers. In fact, I would recommend this so that when students compare costs to a fixed value, they may notice that a fixed value will eventually be too small for longer paths.

**Comment by AndyAtUdacity** [comment]
This doesn't seem like a problem to me and probably more trouble then it's worth to fix. I will reassign to you @JonathanKSullivan if you want to fix it.

**Comment by JonathanKSullivan** [comment]
@AndyAtUdacity , I think you are right about modifying the map. However, I'm going to add a line to the notebook explaining that the mao is literal
