### ISSUE TITLE
Implement Route Planner Project

### ISSUE THREAD

**Issue by mpbGh17** [udacity/isdc_issues_tracker#152]
My Jupyter "Notebook - Implement Route Planner" project directory contains a file called solution.py. Why was that project solution placed in my directory?  I discussed the issue with my mentor and he suggested that I look at the waffle board postings to see if the issue had been raised, and if not post the issue for resolution. Thank you.

**Comment by andrewsdc** [comment]
Hi thanks for posting this and apologies for taking a few weeks to get back to you.  I just opened the project.  I don't see the solution.py anymore. So it looks like it was removed. My guess is that the content developer who designed the project left that file in by mistake and has since removed it. In your classroom, you'll probably still see it unless you reset the workspace. I don't recommend you reset the workspace, however, because you'll lose your work.

**Comment by mpbGh17** [comment]
Thank you!
