### ISSUE TITLE
"All Changes Saved" message is unreliable

### ISSUE THREAD

**Issue by xperroni** [udacity/isdc_issues_tracker#154]
Sometimes the "All Changes Saved" message at the bottom of lesson notebooks is on even though there are unsaved changes.

**Comment by andrewsdc** [comment]
Thanks for letting us know. I'll mention this to the engineering team in charge of this classroom feature.

**Comment by andrewsdc** [comment]
Speaking with the engineering team. Sounds like that message pops up whenever you type something. When you're working with Jupyter notebooks, you're correct that it doesn't save everything as you type even though that message implies things are being saved. 

Seems like the constant saving as you type only happens when you are editing text files like .py files and .cpp files. I'm going to close this issue since they've said they plan to remove the "All Changes Saved" message for the Jupyter notebooks.
