### ISSUE TITLE
Inconsistent behavior when hitting <Enter> after submitting correct answer

### ISSUE THREAD

**Issue by xperroni** [udacity/isdc_issues_tracker#158]
In some quizzes (e.g. Lesson 8.17), hitting <Enter> after the confirmation dialog is displayed in response to a correct answer makes focus return to the question. It would be more natural if it advanced to the answer video. This behavior can in fact be obtained by pressing <Tab> before <Enter>.

**Comment by andrewsdc** [comment]
Hey this is a good point. It would make sense if clicking on continue and hitting enter had the same action. These videos with embedded quizzes are an older style of content. The current style is to separate quizzes and videos from each other. I'll mention your feedback to engineering. But there probably won't be any changes since we aren't making videos with embedded quizzes anymore.
