### ISSUE TITLE
In 3. Working With Matrices, Lesson 3: 18. Instantiate Multiple Cars : when I instantiate multiple cars, it instantiate multiple worlds (each car live in a different world) even though I did not instantiate new world. Is there a way to put them in the same world?

### ISSUE THREAD

**Issue by bcko** [udacity/isdc_issues_tracker#20]

**Comment by cezannec** [comment]
Hi! in this lesson, the cars are meant to keep track of their own state and world, and so there is no easy way to put them in the same world. the only way to do so would be to change car.py file and the display_word function; if you'd like to do that, I'd suggest trying your hand at coding your own car class or modifying the current car.py code so that you can create and move two cars at once; keeping track of two states and paths and so on.

**Comment by bcko** [comment]
Thank you for your clarification! :+1:
