### ISSUE TITLE
ISDC - General Comments

### ISSUE THREAD

**Issue by ganeshnarayan** [udacity/isdc_issues_tracker#221]

**Comment by ganeshnarayan** [comment]
Hi Jonathan,
I did my coding & evaluation in VS. All my code testing came out successful per the validation that is built into the code.
But it took a lot of hours, almost line by line code validation using couts.
I have already submitted my project for review.

This project left a lot to be desired.

* The directives were incorrect
* The instructions were wrong
* The provided code was not structured for VS, which by the way, was the advised editor/compiler in the coursework
* .... and some more.

As I indicated earlier on, you guys really have to look at having a complete write-up on the project - a functionality recap with almost every function meaningfully elaborated to indicate its purpose & what it is doing. Barring that, the understanding of what is happening would be left pretty barren and the project would be done only for getting the project right, but not to have an understanding of what that project does in the broader context of SDC.

**Comment by mvirgo** [comment]
Thank you for your feedback! We have since updated this project to appropriately utilize header files, added some helpful tips and tricks prior to the project, fixed a couple test issues/inconsistencies, as well as created an in-classroom Workspace where the coding can be done. 

Part of the additional tips and tricks makes it a little more obvious how to "visualize" the results at the end, so I'm hoping that better shows off how this actually relates to SDC and robotics.
