### ISSUE TITLE
joy ride bug

### ISSUE THREAD

**Issue by colowl** [udacity/isdc_issues_tracker#230]
i am doing the first exercise and get this error around step 4.

**Comment by colowl** [comment]
![joyridebug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b34025f1328d00011ba60a3/125516c66e82c728ace21e0d46e29b83318b87ac8dfcb801e81fe086264c22703d46f96925dce171ea162f035f5c47f8455f5f44fdab8f7df2b23826984019af80330b2b9b645bf9fa9015ad00b22a8a4a86b6bd8949c3ea3e21e2899d02.PNG)

**Comment by cjander18** [comment]
In case it helps any these are the JS errors I'm getting. The 'SetFullscreen' bug happens when I click the green expand button (whether the screen has been maximized or not the behavior is the same). The 'SendMessage' errors occur any time I try to execute the 'Code Cell' block from jupyter.
![joyride_js_errors.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b342d624e122a0012a57bc6/125516c66e82c728ace21e0d46e29b83318b87acb0e3ac7ca14fe29b3b55653f6b14b1247a80e03cfd183954560d47a9455c0d44fff0dd2fa1b63c71d85a5db9d5690966da2f53fde6d640e258f075c95d8fa4bd8246c1ed3e25e68f894b3d16061c89ed10.PNG)

**Comment by cjander18** [comment]
I was using Chrome Version 67.0.3396.87 64-bit when I first saw this behavior. I updated to Chrome Version 67.0.3396.99 64-bit and relaunched and the issue persisted.

**Comment by shauryakapoor** [comment]
I am having the same issue and I am not sure how to fix it. 

I tried opening it up in Safari but it did not work. I also tried a couple of other things like entering the incognito mode, changing the kernels but nothing seems to work.

**Comment by mvirgo** [comment]
We've changed around a few things on the back-end around how this simulator is launched and run, especially for Chrome, but I think it will likely also help with Safari. We aren't having any current reports on further issues here, but anyone else should feel free to comment here if they see a similar issue, or to open a new ticket if it seems like something new.
